Src install
datasnakes/rinse pull request #18
Opened 2019-03-27 19:30 UTC by grabear

I completely reworked rinse so that it matches the design pattern of renv.  I will give an outline of these changes shortly.

2019-03-27 19:49 UTC, grabear commented
# Surface level changes:

* Removed installr.sh
* Added core.py.
* Added a cookiecutter template for initializing rinse

# Internal Changes:

* Added `InstallR` class
  * Added `LInstallR` subclass
  * Added shell for `WInstallR` and `MacInstallR` subclasses
  * Added source installation as default (`use_source`)
  * Added shell spack/local installation methods for future development (`use_spack`, `use_local`)
* Added init functionality
   * rinse --init creates ~/.beRi/.rinse folder system
   * rinse --init adds the appropriate environment variables (e.g. ~/.beRi/.rinse/bin)
![image](https://user-images.githubusercontent.com/20953530/55107194-ada77b00-509e-11e9-893f-5c52a44f32ed.png)
  * The `src` dir is the cache for the tarballs
  * The `tmp` dir is the target of any tar extractions
  * The `lib` dir is the final installation directory
  * The `bin` dir is where the "global" R/Rscript will be.
    * Added --global option for switching between versions of R via symlink in ~/.beRi/.rinse/bin

# --help Output:

```shell
[grabear@fakenews ~ $]  rinse --help
Usage: rinse [OPTIONS]

Options:
  --install TEXT           Select the version of R to install.
  -g, --global TEXT        Select the version of R available to your global
                           environment.
  -r, --repos TEXT
  --source                 [default: True]
  --spack                  [default: False]
  --local                  [default: False]
  -p, --path TEXT          Select a relative installation path for rinse.
                           [default: ~/.beRi]
  -n, --name TEXT          Select a name for the installation directory for R.
                           [default: .rinse]
  -i, --init               Initialize rinse using the /<path>/<name>.
                           [default: False]
  --config_file TEXT       A text file for sending commands to the configure
                           script that configures R to adapt to many kinds of
                           systems.
  --config_help TEXT       Display the help message for configuring R.
                           [default: False]
  -c, --config_clear TEXT  Remove any files associated with previous attempts
                           to install R.  [default: all]
  --help                   Show this message and exit. 
```

2019-03-29 04:58 UTC, sdhutchins commented
My main comment is maybe we could just write out the classes fully like:

```python
LinuxInstall(InstallR)
```

Otherwise, it looks clean. I'll check it out tomorrow and test/play around.

2019-03-29 15:14 UTC, grabear commented
@sdhutchins thanks!  I'm going to try and merge src_install2 -> src_install today.  It will make way more sense.

2019-03-31 05:09 UTC, santina commented on rinse/utils.py
> +
remove the new line

2019-03-31 05:12 UTC, santina commented
I don't know @click and the code base of this project. Deferring code review to Bruno.  :)

2019-04-01 00:49 UTC, sdhutchins requested changes
Conceptually, it looks good. I made a few suggestions. I'm still testing it, but so far it's working.

2019-04-01 00:49 UTC, sdhutchins commented on rinse/core.py
> +        if init is True:
```suggestion
        if init:
```
Can shorten this and make it more pythonic.

2019-04-01 00:49 UTC, sdhutchins commented on rinse/core.py
> +                    prof_proc = sp.Popen(["source %s" % bash_prof], shell=True)
Use a `try/except` here.

2019-04-01 00:49 UTC, sdhutchins commented on rinse/core.py
> +    def source_make(self, without_make, check, install, install_info, install_pdf, install_tests):
Could be a good idea to write a sp.Popen function with a try/except to use for this.

2019-04-01 00:49 UTC, sdhutchins commented on rinse/core.py
> +        if Path(self.bin_path / "R").exists():
It may better to use one if statement with an or here.
https://github.com/datasnakes/rinse/blob/5987a5c2e34d796fe5bfe7f257066cc784b9f23e/rinse/core.py#L161-L164

2019-04-01 00:49 UTC, sdhutchins commented on rinse/core.py
> +                         init=init)
Could just add the error to the init so when the class is called the error is immediate.
```python  
  def __init__(self, path, version, repos, method, name, init):
        super().__init__(path=path, version=version, repos=repos, method=method, name=name,
                         init=init)
        raise NotImplementedError("Installation of R with rinse on Windows is not supported at this time.")
```

2019-04-01 00:49 UTC, sdhutchins commented on rinse/rinse.py
> +    installR = ctx.obj['installR']
I would go with a lower case variable here `installr`

2019-04-02 23:08 UTC, grabear commented on rinse/rinse.py
> +    installR = ctx.obj['installR']
I would normally agree with you, but this was meant to differentiate this variable from the other similar ones (installer, install).  It also matches with the 4 classes that it is calling (BaseInstallR, LinuxInstallR. etc).

I definitely want to change this in the future.  So for now I'm going to create an issue.

2019-04-02 23:10 UTC, grabear commented on rinse/rinse.py
> +    installR = ctx.obj['installR']
See #19

2019-04-02 23:12 UTC, grabear commented on rinse/core.py
> +    def source_make(self, without_make, check, install, install_info, install_pdf, install_tests):
For line 121, 114 through 121, or for any Popen call? @sdhutchins

2019-04-03 02:48 UTC, sdhutchins commented on rinse/core.py
> +    def source_make(self, without_make, check, install, install_info, install_pdf, install_tests):
@grabear for any.

Then you could have a function like `call_cmd` that has a `try/except` without having to write all of that out.

2019-04-03 02:50 UTC, sdhutchins commented on rinse/rinse.py
> +    installR = ctx.obj['installR']
Good idea.

2019-04-03 20:33 UTC, grabear commented
@sdhutchins please check this out again, and let me know what you think.

2019-04-03 20:53 UTC, sdhutchins commented
I'm currently getting an error when trying to run rinse.

```python
Traceback (most recent call last):
  File "/home/ums/r2295/anaconda3/bin/rinse", line 6, in <module>
    from rinse.rinse import rinse
  File "/ddn/home5/r2295/anaconda3/lib/python3.6/site-packages/rinse/rinse.py", line 2, in <module>
    from rinse.core import BaseInstallR
  File "/ddn/home5/r2295/anaconda3/lib/python3.6/site-packages/rinse/core.py", line 11, in <module>
    from rinse.utils import system_cmd
  File "/ddn/home5/r2295/anaconda3/lib/python3.6/site-packages/rinse/utils.py", line 2, in <module>
    from rinse.core import LinuxInstallR, MacInstallR, WindowsInstallR
ImportError: cannot import name 'LinuxInstallR'
```

2019-04-03 21:23 UTC, grabear commented
> I'm currently getting an error when trying to run rinse.
> 
> ```python
> Traceback (most recent call last):
>   File "/home/ums/r2295/anaconda3/bin/rinse", line 6, in <module>
>     from rinse.rinse import rinse
>   File "/ddn/home5/r2295/anaconda3/lib/python3.6/site-packages/rinse/rinse.py", line 2, in <module>
>     from rinse.core import BaseInstallR
>   File "/ddn/home5/r2295/anaconda3/lib/python3.6/site-packages/rinse/core.py", line 11, in <module>
>     from rinse.utils import system_cmd
>   File "/ddn/home5/r2295/anaconda3/lib/python3.6/site-packages/rinse/utils.py", line 2, in <module>
>     from rinse.core import LinuxInstallR, MacInstallR, WindowsInstallR
> ImportError: cannot import name 'LinuxInstallR'
> ```

Try now.  Everything should be accessible in the top-level rinse module now:

```python
import rinse
rinse.LinuxInstallR(...)
```

2019-04-03 21:37 UTC, sdhutchins commented
Quick example to the readme and to me? lol

2019-04-03 21:37 UTC, sdhutchins commented
Good work on that bug fix.

2019-04-03 21:38 UTC, grabear commented
> Quick example to the readme and to me? lol

I can't give you an example from the Python Interpreter, but I can give you a command line example.

One sec..

2019-04-03 22:06 UTC, sdhutchins commented
> > Quick example to the readme and to me? lol
> 
> I can't give you an example from the Python Interpreter, but I can give you a command line example.
> 
> One sec..

Awesome. I just want something quick that I can try out.

2019-04-03 23:54 UTC, sdhutchins submitted a review, later dismissed

2019-04-03 23:55 UTC, sdhutchins commented
RE: subprocess stuff we discussed...take a look at https://andrewjorgensen.com/post/a-tale-of-two-pipes/

2019-04-04 00:06 UTC, sdhutchins approved these changes

2019-04-04 00:06 UTC, merged

2019-04-04 00:07 UTC, grabear commented
> RE: subprocess stuff we discussed...take a look at https://andrewjorgensen.com/post/a-tale-of-two-pipes/

@sdhutchins I used the strategy in this stackoverflow post:
https://stackoverflow.com/questions/29558074/output-of-subprocess-both-to-pipe-and-directly-to-stdout